development:
  clients:
    default:
      uri: mongodb://nexamind:nexamind1@ds135724.mlab.com:35724/nexamind
      # options:
      #   raise_not_found_error: false
test:
  clients:
    default:
      uri: mongodb://nexamind:nexamind1@ds135724.mlab.com:35724/nexamind
      # options:
      #   raise_not_found_error: false

production:
  clients:
    default:
      uri: mongodb://nexamind:nexamind1@ds135724.mlab.com:35724/nexamind
  defaults: &defaults
  # use_utc: false
  # use_activesupport_time_zone: true

  # options:
  #    raise_not_found_error: false
