development:
  clients:
    default:
      uri: mongodb://shashank.tripathi:Mobiloitte1@ds022228.mlab.com:22228/centareum_app
      # options:
      #   raise_not_found_error: false
test:
  clients:
    default:
      uri: mongodb://shashank.tripathi:Mobiloitte1@ds022228.mlab.com:22228/centareum_app
      # options:
      #   raise_not_found_error: false

production:
  clients:
    default:
      uri: mongodb://shashank.tripathi:Mobiloitte1@ds022228.mlab.com:22228/centareum_app
  defaults: &defaults
  # use_utc: false
  # use_activesupport_time_zone: true

  # options:
  #    raise_not_found_error: false
